# Вычислительная математика

Семинар 2.

* Векторные и матричные нормы

## Норма

* Пусть $V$ - вещественное или комплексное векторное пространство, $f(x)$ - неотрицательная функция, определенная на элементах $x \in V$. Функция называется нормой, если она обладает следующими свойствами:

    1. $f(x) \ge 0 \; \forall x \in V$; $f(x) = 0 \Leftrightarrow x = 0$;
    2. $f(\alpha x) = |\alpha|f(x)$, $\forall \alpha \in \mathbb{R}$ ( или $\mathbb{C})$
    3. $f(x+y) \le f(x) + f(y)$ (неравенство треугольника)
    
$\forall p \ge 1$ функция

$\displaystyle ||x||_p = \left(\sum_{i=1}^{n} |x_i|^p \right)^{1/p}$

является нормой и называется "$p$-норма вектора". К $p$-нормам относят также 
$\displaystyle ||x||_\infty = \lim_{p \to \infty} ||x||_p = \max_i|x_i| $
<center> <img src="L^p unit balls.png" width="600"/></center>

## Матричные нормы

**Определение** $||A||$ называется матричной нормой, если:

1. на векторном пространстве матриц одинакового размера $||A||$ является векторной нормой
2. для любых матриц $A$ и $B$ допускающих умножение выполняется: $\displaystyle ||AB|| \le ||A|| \;||B||$ (мультипликативность)

* Пример матричной нормы - *норма Фробениуса*: 

$\displaystyle ||A||_F = \left(\sum_{i=1}^m \sum_{j=1}^n |a_{ij}|^2\right)^{1/2}$

**Задача: докажите, что $||\cdot||$ является матричной нормой.**

## Операторные нормы

Пусть $P$ действует из $X$ в $Y$ (нормированные пространства). Тогда 

$\displaystyle||P|| = \sup_{x \ne 0} \frac{||Px||_Y}{||x||_X}$

* **Задача: выведите формулы для вычисления $||A||_1$ и $||A||_\infty$ по элементам $A$.**  
* **Задача: докажите, что $||A^T A||_1 \le ||A||_1 \; ||A||_2$**


In [3]:
%matplotlib inline 
import numpy as np

n = 10
a1 = np.array([0,1,2,3]) # так можно создать массив по списку
print('type(a1[0]) = ', type(a1[0])) # Обратите внимание на тип
a2 = np.array([0.0,1,2,3]) # Один из элементов - float
print('type(a2[0]) = ', type(a2[0])) # Обратите внимание на тип

a3 = np.zeros((10)) # np.zeros() и np.ones() по умолчанию имеют тип float64
print('type(a3[0]) = ', type(a3[0])) # Обратите внимание на тип

A = np.zeros((3,3)) # Так можно создать 2D массив из нулей
A = np.random.rand(3,3)
print('A = \n', A)

x = np.ones(3)
b = A @ x # @ - матрично-векторное умножение
b = np.dot(A,x) # это работает для массивов любой размерности
y = np.linalg.solve(A,b) # решаем линейную систему
print('x - y = ', x-y)

l = np.linalg.eigvals(A) # Вычисляются собственные числа
print('l = ', l)
A_1 = np.linalg.norm(A,1)
print('||A||_1 = ', A_1)
# ?np.linalg.solve # так можно вывести документацию для функции
D = np.diag(np.diag(A)) # Так можно взять диагональную часть A
print(D)
Ainv = np.linalg.inv(A) # Обратная матрица
AT = A.T # Транспонирование

type(a1[0]) =  <class 'numpy.int32'>
type(a2[0]) =  <class 'numpy.float64'>
type(a3[0]) =  <class 'numpy.float64'>
A = 
 [[0.48879068 0.49450459 0.54595461]
 [0.48771999 0.18742332 0.8121322 ]
 [0.69148248 0.3540396  0.33218562]]
x - y =  [-2.22044605e-16  0.00000000e+00  2.22044605e-16]
l =  [ 1.4633914 +0.        j -0.22749589+0.15521354j -0.22749589-0.15521354j]
||A||_1 =  1.6902724319831557
[[0.48879068 0.         0.        ]
 [0.         0.18742332 0.        ]
 [0.         0.         0.33218562]]


## Задания

* Попробуйте создать матрицы (2d массивы) различными способами: по списку списков, заполняя в цикле значениями, случайным образом.
* Вычислите и напечатайте нормы 1,2 и $\infty$ для этих матриц
* Вычислите и напечатайте максимальный модуль собственного числа. Как он соотносится с нормами матриц? Докажите, что так будет всегда

In [ ]:
# Ваш код здесь:

## Простейший итерационный метод 

* $Ax = b$
* Разобьем матрицу $A$ на 2 матрицы   
    $A = M - N$

* $M x = N x + b \Rightarrow x = M^{-1} (N x + b)$  
$M$ должна быть обратимой

* $x^{(k+1)} = M^{-1} (N x^{(k)} + b)$

* как будет меняться ошибка $e_k = x_k -x$ от итерации к итерации? (на доске)

## Метод Якоби

* Чтобы получить выигрыш, нужно чтобы решение системы с матрицей $M$ было быстрым
* Линейная система с какой матрицей решается за $\mathcal{O}(n)$ операций?

* В методе Якоби матрица $M = D$ - диагональная часть матрицы $A$
* При каком условии $||D^{-1} N||_{1,\infty} < 1$? (на доске)

## Задание

1. Реализуйте какой-либо способ создания случайной матрицы со свойством $||D^{-1} N||_1 < 1$
2. Реализуйте итерационный метод $x^{(k+1)} = D^{-1} (N x^{(k)} + b)$
3. Постройте график зависимости логарифма нормы ошибки $e^{(k)} = x_k - x$ от числа итераций. График можно построить с помощью функции matplotlib.pyplot.semilogy(error_array)

In [4]:
# Так можно измерить время
import time

start = time.time()
a = 0
for i in range(10**5):
    a += 1/(i+1)
end = time.time()
print('time = ', end - start)

time =  0.020000934600830078


In [11]:
%%time 
# Так тоже можно измерить время исполнения данной ячейки
a = 0
for i in range(10**5):
    a += 1/(i+1)
end = time.time()

Wall time: 26 ms


## Некоторые классы матриц
* Унитарные
* Эрмитовы
* Нормальные
* Знакоопределенные


1. Пусть $A$ - эрмитова, $A >0$. Докажите, что при достаточно малых $\alpha$ матрица $B = I -\alpha A$ будет сходящейся (т.е. $\rho(B) = \max_k \lambda_k(B) < 1$).

## Сингулярное разложение (SVD)
0. Докажите, что $\Vert A\Vert_2 = \sigma_1$ (максимальное сингулярное число)
1. Как получить $ker(A)$, $image(A)$ через SVD? 
2. Обратная матрица через SVD
## Обусловленность
3. Обусловленность линейной системы при разных правых частях
4. Как обусловленность связана с $det(A)$?

## SVD и малоранговые приближения

Наилучшее приближение матрицы матрицей малого ранга вычисляется через SVD: 

**Теорема(Эккарта-Янга)** Пусть $r < \text{rank}(A)$, $A_r = U_r \Sigma_r V_r^*$. Тогда

$$
    \min_{\text{rank}(B)=r} \|A - B\|_2 = \|A - A_r\|_2 = \sigma_{r+1}.
$$

Для фробениусовой нормы:$\|A - A_r\|_F = \sqrt{\sigma_{r+1}^2 + \dots + \sigma_{\min (n,m)}^2}$.

In [25]:
%matplotlib inline
import numpy as np
from matplotlib import pyplot as plt

A = np.random.rand(6,3)
u, s, v = np.linalg.svd(A) # Так вычисляется SVD, V - это V^* в наших обозначениях
print('Shapes:', u.shape, s.shape, v.shape) # s - не матрица, а вектор!
# Так можно построить декартову сетку:
tx = np.linspace(0, 1, 3) # Узлы по x
ty = np.linspace(0, 1, 6) # узлы по y
X, Y = np.meshgrid(tx, ty) # X,Y - 2D массивы
print(X)
print(Y)
f = np.sin(X**2 + Y**2) # Массив значений функции на сетке



Shapes: (6, 6) (3,) (3, 3)
[[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
[[0.  0.  0. ]
 [0.2 0.2 0.2]
 [0.4 0.4 0.4]
 [0.6 0.6 0.6]
 [0.8 0.8 0.8]
 [1.  1.  1. ]]


## SVD и малоранговые приближения

Задача: вычислить приближенно интеграл от функции $f(x,y)$ по прямоугольнику $[x_l,x_r]\times[y_l,y_r]$ с помощью SVD
1. Интеграл примерно равен $\sum_{i,j} f(x_i,y_j) dx dy$, где  $(x_i,x_j)$ - центры прямоугольников со сторонами $dx,dy$, на которые разбита область

2. Создайте 2D массив (матрицу), заполненную значениями функции в этих точках

3. "Обрежьте" матрицу до $\hat{A}$ с помощью SVD до заданной точности $tol \approx 10^{-3}$  или до заданного ранга $r$

4. Найдите интеграл как сумму $dx dy\sum_{i,j} \hat{A}(i,j)$, не вычисляя элементы матрицы $\hat{A}$, а используя SVD

5. Придумайте функцию, для которой интеграл можно вычислить аналитически, постройте график зависимости ошибки в значении интеграла от ранга $r$ приближенной матрицы